### ISSUE TITLE
Cannot display asterisk

### ISSUE THREAD

**Issue by rzuckerm** [stuin/Solisp#1]
I'm trying to modify the Baklava sample program so that it display asterisks (`*`) instead of pound signs (`#`). If I do this:
```
(Join (Map x (Append (Seq 0 10) (Reverse (Seq 0 9)))
	(Join (Append
		(Clone (- 10 x) " ")
		(Clone (+ (* x 2) 1) "*")
	))
) "\n")
```
then I get a bunch of `<:func>` symbols instead of `*`. How do I display an asterisk?

**Comment by stuin** [comment]
This is a case of list evaluation being too quick at resolving variables. I have had some small issues with this category of things before but this is a much more definite problem as it will limit using any arithmetic operator in strings.

Sorry, I would prefer that this worked with no issue, and even so there was supposed to be a workaround for this using `"\*"` or `":*"`, but as it is happening to each individual character it is ignoring that and there is no simple solution in language.

This will require an update to the language as I need to properly figure out and define where variables should and should not be resolved.

**Comment by rzuckerm** [comment]
Could you maybe get around the problem by creating a new operation called `Chr`? That way, `*` could be displayed like this:
```
(Chr 42)
```

**Comment by stuin** [comment]
New version has been created that splits Names and Strings into mostly separate data types, names without quotes will be checked as variable names before being used as Strings, Strings with quotes will not be resolved as variable names without specific effort.
Also adjusted some stuff with Lists and added a Force function to directly convert types.

Your suggested code should work, but so would this adjusted version below
```
(JoinD newline (Map x (Append (Seq 0 10) (Reverse (Seq 0 9)))
        (Append
                (Clone (- 10 x) " ")
                (Clone (+ (* x 2) 1) (Force Char 42))
        )
))
```
I also wanted to fix Join to not need an optional argument and make use of List features better, but that would break all my examples so I guess Join is just a bit deprecated and JoinD is a thing.
