### ISSUE TITLE
Arguments with space are truncated

### ISSUE THREAD

**Issue by rzuckerm** [stuin/Solisp#2]
```lisp
(If (== (Length args) 0)
	""
	(If (== (Length (Get 0 args)) 0)
		""
		(Reverse (Get 0 args))
	)
)
```

If the first argument is "Hello", the output is "olleH" like expected. If the first argument is "Hello World", the output is still "olleH"

**Comment by stuin** [comment]
Fixed

**Comment by rzuckerm** [comment]
Why was this closed?

**Comment by stuin** [comment]
Fixed, arguments were being read as without quotes
